name: spinify

description: >
  Dart client to communicate with Centrifuge and Centrifugo from Dart and Flutter
  over WebSockets with Protobuf support.

version: 0.2.0

homepage: https://centrifugal.dev

repository: https://github.com/PlugFox/spinify

issue_tracker: https://github.com/PlugFox/spinify/issues

funding:
  - https://www.buymeacoffee.com/plugfox
  - https://www.patreon.com/plugfox
  - https://boosty.to/plugfox

topics:
  - spinify
  - centrifugo
  - centrifuge
  - websocket
  - cross-platform

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

#screenshots:
#  - description: 'Example of using the library to connect to a Centrifugo server.'
#    path: example.png


environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  # Annotations
  meta: ^1.9.1

  # Protocol Buffers
  protobuf: ">=3.1.0 <5.0.0"

  # Web related libraries
  web: ^1.0.0

  # Utilities
  crypto: ^3.0.3
  fixnum: ^1.1.0
  stack_trace: ^1.11.0

dev_dependencies:
  build_runner: ^2.4.10
  pubspec_generator: ^4.1.0-pre.1
  benchmark_harness: ^2.2.2
  lints: '>=4.0.0 <6.0.0'
  test: ^1.25.8
  fake_async: ^1.3.2
  mockito: ^5.0.0
  # https://github.com/dart-lang/mockito/issues/732
  # https://github.com/dart-lang/mockito/pull/738
  # https://github.com/dart-lang/mockito/issues/755
  #mockito:
  #  git:
  #    url: https://github.com/dart-lang/mockito.git
  #    ref: master
